### ISSUE TITLE
ECO not started. Please fix it. Paper 1.18.2

### ISSUE THREAD

**Issue by Futodama** [Auxilor/eco#103]
[12:36:17] [Server thread/ERROR]: [eco] Fatal error with proxies! This plugin can't load.
[12:36:17] [Server thread/ERROR]: Could not load 'plugins\eco-6.26.3-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: com.willfp.eco.core.proxy.exceptions.ProxyError: Could not initialize proxy.
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[paper-1.18.2.jar:git-Paper-219]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-219]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-219]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-219]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.willfp.eco.core.proxy.exceptions.ProxyError: Could not initialize proxy.
	at com.willfp.eco.internal.proxy.EcoProxyFactory.proxyErrorFrom(EcoProxyFactory.kt:47) ~[eco-6.26.3-all.jar:?]
	at com.willfp.eco.internal.proxy.EcoProxyFactory.getProxy(EcoProxyFactory.kt:37) ~[eco-6.26.3-all.jar:?]
	at com.willfp.eco.core.EcoPlugin.getProxy(EcoPlugin.java:681) ~[eco-6.26.3-all.jar:?]
	at com.willfp.eco.internal.spigot.EcoSpigotPlugin.<init>(EcoSpigotPlugin.kt:164) ~[eco-6.26.3-all.jar:?]
	at com.willfp.eco.internal.spigot.EcoHandler.<init>(EcoHandler.kt:41) ~[eco-6.26.3-all.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 7 more
Caused by: com.willfp.eco.core.proxy.exceptions.UnsupportedVersionError: You're running an unsupported server version: v1_18_R2
	at com.willfp.eco.internal.proxy.EcoProxyFactory.proxyErrorFrom(EcoProxyFactory.kt:49) ~[eco-6.26.3-all.jar:?]
	at com.willfp.eco.internal.proxy.EcoProxyFactory.getProxy(EcoProxyFactory.kt:37) ~[eco-6.26.3-all.jar:?]
	at com.willfp.eco.core.EcoPlugin.getProxy(EcoPlugin.java:681) ~[eco-6.26.3-all.jar:?]
	at com.willfp.eco.internal.spigot.EcoSpigotPlugin.<init>(EcoSpigotPlugin.kt:164) ~[eco-6.26.3-all.jar:?]
	at com.willfp.eco.internal.spigot.EcoHandler.<init>(EcoHandler.kt:41) ~[eco-6.26.3-all.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 7 more

**Comment by WillFP** [comment]
1.18.2 support is coming in the next update. Please be patient
