### ISSUE TITLE
Error occurred while disabling eco

### ISSUE THREAD

**Issue by mani1232** [Auxilor/eco#130]
**Describe the bug**
[17:23:23 ERROR]: Error occurred while disabling eco v6.33.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/willfp/eco/core/items/CustomItem
        at com.willfp.eco.core.items.Items.getCustomItems(Items.java:380) ~[eco-6.33.0-all.jar:?]
        at com.willfp.eco.internal.EcoCleaner.clean(EcoCleaner.kt:18) ~[eco-6.33.0-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.onDisable(EcoPlugin.java:433) ~[eco-6.33.0-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:593) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:570) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:494) ~[pearl-1.18.2.jar:git-Pearl-"f2e8f01"]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:984) ~[pearl-1.18.2.jar:git-Pearl-"f2e8f01"]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:846) ~[pearl-1.18.2.jar:git-Pearl-"f2e8f01"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1298) ~[pearl-1.18.2.jar:git-Pearl-"f2e8f01"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[pearl-1.18.2.jar:git-Pearl-"f2e8f01"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**To Reproduce**
/stop

**Expected behavior**

**Screenshots**

**Server Information (please complete the following information):**
- Version: 1.18.2 Pearl (fork purpur)
- Version of plugin and eco 6.33.0

**Additional context**

**Comment by WillFP** [comment]
Don't worry about it, it doesn't do anything
