### ISSUE TITLE
StackOverflowError from sending BlockBreakEvent -> ecoenchants

### ISSUE THREAD

**Issue by braddevans** [Auxilor/eco#136]
**Describe the bug**
The plugin Eco Could not pass event BlockBreakEvent to EcoEnchants v8.57.2

**To Reproduce**
1. enchant pickaxe with veinminer
2. mine any natural ore

**Expected behavior**
it only happens when breaking ore with the vein miner enchant

**Screenshots**
N/A does not apply since it only happens when breaking ore with the vein miner enchant

**Server Information (please complete the following information):**
- Version: This server is running Paper version git-Paper-313 (MC: 1.18.2) 
- (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 6f5e6c6)
- Version of plugin and eco `eco version 6.35.1`, `EcoEnchants version 8.57.2`

**Additional context**
```
[05:36:59] [Server thread/ERROR]: Could not pass event BlockBreakEvent to EcoEnchants v8.57.2
java.lang.StackOverflowError: null
	at org.bukkit.craftbukkit.v1_18_R2.block.CraftBlock.getType(CraftBlock.java:227) ~[paper-1.18.2.jar:git-Paper-313]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:33) ~[eco-6.35.1-all.jar:?]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all.jar:?]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all.jar:?]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all.jar:?]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all.jar:?]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all.jar:?]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all.jar:?]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all.jar:?]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all.jar:?]
	at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all.jar:?]
```

**Comment by WillFP** [comment]
Fixed in latest eco
