### ISSUE TITLE
Packet error

### ISSUE THREAD

**Issue by TypicalShavonne** [Auxilor/eco#141]
[eco] Unhandled exception number 2048 occured in onPacketSending(PacketEvent) for eco
java.lang.RuntimeException: Unable to clone object PacketContainer[type=WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[private final int net.minecraft.network.protocol.game.PacketPlayOutWindowItems.a, private final int net.minecraft.network.protocol.game.PacketPlayOutWindowItems.b, private final java.util.List net.minecraft.network.protocol.game.PacketPlayOutWindowItems.c, private final net.minecraft.world.item.ItemStack net.minecraft.network.protocol.game.PacketPlayOutWindowItems.d]]] (com.comphenix.protocol.events.PacketContainer)
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:256) ~[ProtocolLib.jar:?]
        at com.willfp.eco.internal.spigot.display.PacketWindowItems.onSend(PacketWindowItems.kt:50) ~[eco-6.35.3-all.jar:?]
        at com.willfp.eco.core.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:119) ~[eco-6.35.3-all.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2072) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2058) ~[?:?]
        at net.minecraft.server.level.ServerPlayer$1.sendInitialData(ServerPlayer.java:273) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.sendAllDataToRemote(AbstractContainerMenu.java:202) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:501) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2843) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pearl-1.18.2.jar:git-Pearl-"8f12a7a"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1412) ~[pearl-1.18.2.jar:git-Pearl-"8f12a7a"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[pearl-1.18.2.jar:git-Pearl-"8f12a7a"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1389) ~[pearl-1.18.2.jar:git-Pearl-"8f12a7a"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1382) ~[pearl-1.18.2.jar:git-Pearl-"8f12a7a"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1460) ~[pearl-1.18.2.jar:git-Pearl-"8f12a7a"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[pearl-1.18.2.jar:git-Pearl-"8f12a7a"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pearl-1.18.2.jar:git-Pearl-"8f12a7a"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1000, banned: 0], return=Exact class net.minecraft.network.protocol.game.PacketPlayOutWindowItems, params=[{Type: Exact class net.minecraft.network.PacketDataSerializer, Index: 0}], paramCount=1}
        at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:330) ~[ProtocolLib.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor193.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1231) ~[?:?]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2434) ~[?:?]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2268) ~[?:?]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:514) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:472) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[ProtocolLib.jar:?]
        ... 40 more

**Comment by TypicalShavonne** [comment]
https://timin.gs/?id=b8957495316a4bb495d5da4a847135d7
eco is making my server lagging so badly

**Comment by WillFP** [comment]
For performance: drop a spark profile
For packet error: disable everything under async-display in eco config.yml
