### ISSUE TITLE
Mongo migration failure

### ISSUE THREAD

**Issue by Booquefius** [Auxilor/eco#152]
**Describe the bug**
Mongo fails to migrate

**To Reproduce**
1. Change to mongo from mysql 
2. Start

**Expected behavior**

**Screenshots**

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)

eco 6.36.4

**Additional context**
```
[16:51:57] [Server thread/INFO]: [eco] eco has detected a change in data handler!
[16:51:57] [Server thread/INFO]: [eco] Migrating server data from MYSQL to MONGO
[16:51:57] [Server thread/INFO]: [eco] This will take a while!
[16:51:57] [Server thread/INFO]: [eco] Found data for 241 players!
[16:51:57] [Server thread/INFO]: [eco] Migrating data for 1854f75a-67c9-443b-94e4-af24cb5f8004... (1 / 241)
[16:51:57] [Server thread/ERROR]: Error occurred while enabling eco v6.36.4 (Is it up to date?)
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: org.jetbrains.exposed.dao.id.UUIDTable.ecoskills:points_ is not in record set
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.willfp.eco.internal.spigot.data.storage.ImplementedMySQLHandler.read(MySQLDataHandler.kt:226) ~[eco-6.36.4-all.jar:?]
	at com.willfp.eco.internal.spigot.data.storage.MySQLDataHandler.read(MySQLDataHandler.kt:90) ~[eco-6.36.4-all.jar:?]
	at com.willfp.eco.internal.spigot.data.EcoProfileHandler.migrateIfNeeded$migrateKey(EcoProfileHandler.kt:105) ~[eco-6.36.4-all.jar:?]
	at com.willfp.eco.internal.spigot.data.EcoProfileHandler.migrateIfNeeded(EcoProfileHandler.kt:116) ~[eco-6.36.4-all.jar:?]
	at com.willfp.eco.internal.spigot.data.EcoProfileHandler.initialize(EcoProfileHandler.kt:137) ~[eco-6.36.4-all.jar:?]
	at com.willfp.eco.internal.spigot.EcoSpigotPlugin.handleEnable(EcoSpigotPlugin.kt:228) ~[eco-6.36.4-all.jar:?]
	at com.willfp.eco.core.EcoPlugin.onEnable(EcoPlugin.java:413) ~[eco-6.36.4-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:291) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: org.jetbrains.exposed.dao.id.UUIDTable.ecoskills:points_ is not in record set
	at org.jetbrains.exposed.sql.ResultRow.getRaw(ResultRow.kt:76) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.ResultRow.get(ResultRow.kt:22) ~[eco-6.36.4-all.jar:?]
	at com.willfp.eco.internal.spigot.data.storage.ImplementedMySQLHandler$read$doRead$1$1.invoke(MySQLDataHandler.kt:218) ~[eco-6.36.4-all.jar:?]
	at com.willfp.eco.internal.spigot.data.storage.ImplementedMySQLHandler$read$doRead$1$1.invoke(MySQLDataHandler.kt:215) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132) ~[eco-6.36.4-all.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:131) ~[eco-6.36.4-all.jar:?]
	at com.willfp.eco.internal.spigot.data.storage.ImplementedMySQLHandler.read$lambda-3(MySQLDataHandler.kt:215) ~[eco-6.36.4-all.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
[16:51:57] [Server thread/INFO]: [eco] Disabling eco v6.36.4
[16:51:57] [Server thread/INFO]: [eco] Saving player data...
[16:51:57] [Server thread/INFO]: [eco] Saved player data! Took 0ms
[16:51:57] [Server thread/INFO]: [eco] Cleaning up...
```

**Comment by WillFP** [comment]
Known bug - haven't found a solution yet
