### ISSUE TITLE
Eco + Talismans - InventoryCloseEvent bug

### ISSUE THREAD

**Issue by konfix** [Auxilor/eco#159]
**Describe the bug**
There's a bug with /talisman bag. It spams the console after every use of this command. I've also noticed that you can lose your items if you close the inventory while holding the item like in this image:

![Image](https://rs.mysticmc.org/image/0psqr.png) 
(3 cobblestone that haven't been placed in the inventory will be lost after closing.)

**To Reproduce**
1. Type /talisman bag
2. Optional: place any item inside of it
3. Look at the console for errors

**Expected behavior**
Talisman bag without any errors, unplaced items shouldn't be lost on close.

**Screenshots**
(above)

**Server Information (please complete the following information):**
- Version: git-Purpur-1632 (MC: 1.18.2) **LATEST VERSION**
- Version of plugin and eco: eco version 6.37.1, Talismans version 5.77.0 (updated to 5.79.0, same issue)

**Bug**
```
[13:52:55 ERROR]: Could not pass event InventoryCloseEvent to eco v6.37.1
java.lang.NullPointerException: null
        at com.willfp.eco.internal.gui.slot.EcoSlot.getItemStack(EcoSlot.kt:41) ~[eco-6.37.1-all.jar:?]
        at com.willfp.eco.internal.gui.menu.MenuRenderedInventory.generateCaptive(MenuRenderedInventory.kt:43) ~[eco-6.37.1-all.jar:?]
        at com.willfp.eco.internal.gui.menu.EcoMenu.handleClose(EcoMenu.kt:58) ~[eco-6.37.1-all.jar:?]
        at com.willfp.eco.internal.spigot.gui.GUIListener.handleClose(GUIListener.kt:65) ~[eco-6.37.1-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor44.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1550) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2713) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:2706) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by WillFP** [comment]
Fixed in next eco
