### ISSUE TITLE
Could not pass event ShopPreTransactionEvent

### ISSUE THREAD

**Issue by Strahilchu** [Auxilor/eco#182]
[01:36:18 ERROR]: Could not pass event ShopPreTransactionEvent to eco v6.38.2
java.lang.NoSuchMethodError: 'net.brcdev.shopgui.shop.item.ShopItem net.brcdev.shopgui.event.ShopPreTransactionEvent.getShopItem()'
at com.willfp.eco.internal.spigot.integrations.shop.ShopShopGuiPlus$ShopGuiPlusSellEventListeners.shopEventToEcoEvent(ShopShopGuiPlus.kt:53) ~[eco-6.38.2-all.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor68.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:git-petal-"8ba3e6e"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at net.brcdev.shopgui.shop.ShopManager.handleItemSellAll(ShopManager.java:1142) ~[ShopGUIPlus-1.77.3.jar:?]
at net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:420) ~[ShopGUIPlus-1.77.3.jar:?]
at net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:139) ~[ShopGUIPlus-1.77.3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor718.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:git-petal-"8ba3e6e"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3369) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Golumpa** [comment]
So this is actually fixed in the latest eco, but that eco is only compatible with 1.19. This means that this is broken if you aren't using 1.19 with the latest version.

As a quick fix, you could downgrade ShopGUI+ to 1.77.4. However, if you need to use the latest version of ShopGUI+ due to other plugins then you could use my compiled version that has literally 1 line changed in the gradle.build to use the newest API.

https://github.com/Golumpa/eco/commit/c037801f7833a3a462be84a3985519cb6248f366
https://mega.nz/file/lIgWGbSI#oT1Pa2HjK4QjyS9zjLsSvBKeTfy1hPr4nLFJHurUvyE

NOTE: You shouldn't just place any plugin on your server but this is the build I made for myself for my server. The link to my github fork is the only thing I changed.

**Comment by WillFP** [comment]
eco is compatible with all versions 1.17-1.19, you just need the latest protocollib
