### ISSUE TITLE
Incompatibility with MySQLPlayerDataBridge due to ProtocolLib

### ISSUE THREAD

**Issue by AlexanderMoebius** [Auxilor/eco#185]
**Describe the bug**
An NOSuchMethodError occurs

**To Reproduce**
1. Use current eco, ProtocolLib and MysqlPlayerDataBridge

**Expected behavior**
No Error ;)

**Screenshots**

**Server Information (please complete the following information):**
- Version: Paper 1.17.1 - 411
- eco: 6.38.2
- ProtocolLib - 4.8

**Additional context**
`[11:24:57 ERROR]: [eco] Unhandled exception number 128 occured in onPacketSending(PacketEvent) for eco
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.reflect.StructureModifier.modify(int, java.util.function.UnaryOperator)'
        at com.willfp.eco.internal.spigot.display.PacketSetSlot.onSend(PacketSetSlot.kt:20) ~[eco.jar:?]
        at com.willfp.eco.core.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:119) ~[eco.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[app:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1997) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:1983) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:113) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventory.clear(CraftInventory.java:442) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventory.clear(CraftInventory.java:448) ~[patched_1.17.1.jar:git-Paper-411]
        at net.craftersland.data.bridge.events.handlers.InventoryDataHandler.backupAndReset(InventoryDataHandler.java:275) ~[MysqlPlayerDataBridge-v4.5.0.jar:?]
        at net.craftersland.data.bridge.events.handlers.InventoryDataHandler.access$1(InventoryDataHandler.java:270) ~[MysqlPlayerDataBridge-v4.5.0.jar:?]
        at net.craftersland.data.bridge.events.handlers.InventoryDataHandler$2.run(InventoryDataHandler.java:239) ~[MysqlPlayerDataBridge-v4.5.0.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by brunyman** [comment]
I don't think there is much I can do about this
![image](https://user-images.githubusercontent.com/10031766/185968656-fe58b5c1-1a48-4515-9e82-54554cdcf4b4.png)

**Comment by AlexanderMoebius** [comment]
Then probably a problem with ProtocolLib.
eco seems to be build against v5 if I have seen it correct.

Errors occur on every join. But players can't notice any problems. It are just the errors in console...

**Comment by AlexanderMoebius** [comment]
Same error as https://github.com/Auxilor/eco/issues/179

**Comment by Phoenix-99** [comment]
same error, how i can fix it? :(
