### ISSUE TITLE
MySQL ERROR

### ISSUE THREAD

**Issue by LobbyTech-MC** [Auxilor/eco#195]
[11:07:08 INFO]: [com.willfp.eco.libs.hikari.HikariDataSource] HikariPool-1 - Start completed.
[11:07:08 WARN]: [Exposed] Transaction attempt #0 failed: java.sql.SQLSyntaxErrorException: BLOB, TEXT, GEOMETRY or JSON column 'json_data' can't have a default value. Statement(s): ALTER TABLE eco_data ADD json_data longtext DEFAULT '{}' NOT NULL
org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.SQLSyntaxErrorException: BLOB, TEXT, GEOMETRY or JSON column 'json_data' can't have a default value
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:64) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:144) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:130) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:106) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:92) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec$default(Transaction.kt:91) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.SchemaUtils.execStatements(SchemaUtils.kt:248) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns(SchemaUtils.kt:318) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns$default(SchemaUtils.kt:303) ~[eco-6.40.1-all.jar:?]
        at com.willfp.eco.internal.spigot.data.storage.MySQLDataHandler$1.invoke(MySQLDataHandler.kt:73) ~[eco-6.40.1-all.jar:?]
        at com.willfp.eco.internal.spigot.data.storage.MySQLDataHandler$1.invoke(MySQLDataHandler.kt:65) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:131) ~[eco-6.40.1-all.jar:?]
        at com.willfp.eco.internal.spigot.data.storage.MySQLDataHandler.<init>(MySQLDataHandler.kt:65) ~[eco-6.40.1-all.jar:?]
        at com.willfp.eco.internal.spigot.data.EcoProfileHandler.<init>(EcoProfileHandler.kt:30) ~[eco-6.40.1-all.jar:?]
        at com.willfp.eco.internal.spigot.EcoHandler.<init>(EcoHandler.kt:65) ~[eco-6.40.1-all.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:354) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.sql.SQLSyntaxErrorException: BLOB, TEXT, GEOMETRY or JSON column 'json_data' can't have a default value
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031) ~[mysql-connector-java-8.0.27.jar:8.0.27]
        at com.willfp.eco.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[eco-6.40.1-all.jar:?]
        at com.willfp.eco.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:26) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:111) ~[eco-6.40.1-all.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:62) ~[eco-6.40.1-all.jar:?]
        ... 39 more

**Comment by FlueMc** [comment]
Hi, I have the same error... Were you able to solve it?
