### ISSUE TITLE
Spamming errors

### ISSUE THREAD

**Issue by ReformedHooper** [Auxilor/eco#196]
Hello, it keeps spamming me with errors in the console, what can I do to fix it? or is this a bug? Plugin version 6.40.2

[14:45:07 ERROR]: [eco] Unhandled exception occured in onPacketSending(PacketEvent) for eco
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.reflect.StructureModifier.modify(int, java.util.function.UnaryOperator)'
at com.willfp.eco.internal.spigot.display.PacketHeldWindowItems.onSend(PacketHeldWindowItems.kt:19) ~[eco-6.40.2-all.jar:?]
at com.willfp.eco.core.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:119) ~[eco-6.40.2-all.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
at net.minecraft.network.Connection.processQueue(Connection.java:530) ~[?:?]
at net.minecraft.network.Connection.flushQueue(Connection.java:493) ~[?:?]
at net.minecraft.network.Connection.send(Connection.java:401) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2123) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2109) ~[?:?]
at net.minecraft.server.level.ServerPlayer$1.sendInitialData(ServerPlayer.java:277) ~[?:?]
at net.minecraft.world.inventory.AbstractContainerMenu.sendAllDataToRemote(AbstractContainerMenu.java:202) ~[?:?]
at net.minecraft.world.inventory.AbstractContainerMenu.setSynchronizer(AbstractContainerMenu.java:182) ~[?:?]
at net.minecraft.server.level.ServerPlayer.initMenu(ServerPlayer.java:597) ~[?:?]
at net.minecraft.server.level.ServerPlayer.initInventoryMenu(ServerPlayer.java:601) ~[?:?]
at net.minecraft.server.players.PlayerList.onPlayerJoinFinish(PlayerList.java:487) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:424) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:320) ~[?:?]
at net.minecraft.network.Connection.tick(Connection.java:576) ~[?:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1651) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:45:08 ERROR]: Parameters:
net.minecraft.network.protocol.game.PacketPlayOutWindowItems@4aaa0a15[
a=0
b=1
c=[1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 2 end_portal_frame, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air]
d=1 air
]

**Comment by WillFP** [comment]
Update to latest protocollib dev build
