### ISSUE TITLE
Could not load plugin 'eco-6.63.1-all.jar'

### ISSUE THREAD

**Issue by igummie** [Auxilor/eco#277]
I can't get eco to load in any version of 1.20 even though i've downloaded the newest patch that supports 1.20

**To Reproduce**
1. get a paper server
2. add eco.jar
3. start server

**Server Information (please complete the following information):**
- Version: Paper version git-Paper-3 (MC: 1.20) (Implementing API version 1.20-
R0.1-SNAPSHOT) (Git: dc30ee5)
- Version of eco is 6.63.1-all.jar

`[18:34:38 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'eco-6.63.1-all.jar' in folder 'plugin
s'
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.
java:79) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
        at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:60) ~[paper-api-1.
20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:29) ~[paper-api-1.
20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createIns
tance(PaperPluginParent.java:169) ~[paper-1.20.jar:git-Paper-3]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createIns
tance(PaperPluginParent.java:139) ~[paper-1.20.jar:git-Paper-3]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(Mode
rnPluginLoadingStrategy.java:116) ~[paper-1.20.jar:git-Paper-3]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[pape
r-1.20.jar:git-Paper-3]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
 ~[paper-1.20.jar:git-Paper-3]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:431) ~[paper-1.20.jar:gi
t-Paper-3]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.
jar:git-Paper-3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.20.jar:git-Pa
per-3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git
-Paper-3]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' n
ot found
        at com.willfp.eco.internal.config.EcoRepresenter.<init>(EcoRepresenter.kt:9) ~[eco-6.63.1-all.jar:?]
        at com.willfp.eco.internal.config.YamlConfigTypeHandler.newYaml(ConfigUtils.kt:98) ~[eco-6.63.1-all.
jar:?]
        at com.willfp.eco.internal.config.YamlConfigTypeHandler.parseToMap(ConfigUtils.kt:123) ~[eco-6.63.1-
all.jar:?]
        at com.willfp.eco.internal.config.ConfigTypeHandler.toMap(ConfigUtils.kt:86) ~[eco-6.63.1-all.jar:?]
        at com.willfp.eco.internal.config.ConfigUtilsKt.toMap(ConfigUtils.kt:16) ~[eco-6.63.1-all.jar:?]
        at com.willfp.eco.internal.config.EcoLoadableConfig.init(EcoLoadableConfig.kt:94) ~[eco-6.63.1-all.j
ar:?]
        at com.willfp.eco.internal.config.EcoLoadableConfig.init(EcoLoadableConfig.kt:98) ~[eco-6.63.1-all.j
ar:?]
        at com.willfp.eco.internal.config.EcoLoadableConfig.<init>(EcoLoadableConfig.kt:147) ~[eco-6.63.1-al
l.jar:?]
        at com.willfp.eco.internal.config.EcoUpdatableConfig.<init>(EcoUpdatableConfig.kt:19) ~[eco-6.63.1-a
ll.jar:?]
        at com.willfp.eco.internal.spigot.EcoImpl.createUpdatableConfig(EcoImpl.kt:170) ~[eco-6.63.1-all.jar
:?]
        at com.willfp.eco.internal.spigot.EcoImpl.createUpdatableConfig(EcoImpl.kt:77) ~[eco-6.63.1-all.jar:
?]
        at com.willfp.eco.core.config.BaseConfig.<init>(BaseConfig.java:43) ~[eco-6.63.1-all.jar:?]
        at com.willfp.eco.core.config.BaseConfig.<init>(BaseConfig.java:26) ~[eco-6.63.1-all.jar:?]
        at com.willfp.eco.core.config.base.LangYml.<init>(LangYml.java:41) ~[eco-6.63.1-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.createLangYml(EcoPlugin.java:848) ~[eco-6.63.1-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:338) ~[eco-6.63.1-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:180) ~[eco-6.63.1-all.jar:?]
        at com.willfp.eco.internal.spigot.EcoSpigotPlugin.<init>(EcoSpigotPlugin.kt:140) ~[eco-6.63.1-all.ja
r:?]
        at com.willfp.eco.internal.spigot.EcoImpl.<init>(EcoImpl.kt:78) ~[eco-6.63.1-all.jar:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.
java:67) ~[?:?]
        ... 14 more`

**Comment by aadrians1** [comment]
same here
