### ISSUE TITLE
Eco 1.20 loading error

### ISSUE THREAD

**Issue by kylichist** [Auxilor/eco#279]
I get an error with eco during server initialization stage

1. Get spigot mc 1.20 server 
2. Install eco, ecoenchants, ProtocolLib 
3. Start server

`[Server thread/ERROR]: Could not load 'plugins/eco-6.63.1-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:430) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3786-Spigot-ddcbdcc-ce710de]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3786-Spigot-ddcbdcc-ce710de]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3786-Spigot-ddcbdcc-ce710de]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3786-Spigot-ddcbdcc-ce710de]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
	at com.willfp.eco.internal.config.EcoRepresenter.<init>(EcoRepresenter.kt:9) ~[?:?]
	at com.willfp.eco.internal.config.YamlConfigTypeHandler.newYaml(ConfigUtils.kt:98) ~[?:?]
	at com.willfp.eco.internal.config.YamlConfigTypeHandler.parseToMap(ConfigUtils.kt:123) ~[?:?]
	at com.willfp.eco.internal.config.ConfigTypeHandler.toMap(ConfigUtils.kt:86) ~[?:?]
	at com.willfp.eco.internal.config.ConfigUtilsKt.toMap(ConfigUtils.kt:16) ~[?:?]
	at com.willfp.eco.internal.config.EcoLoadableConfig.init(EcoLoadableConfig.kt:94) ~[?:?]
	at com.willfp.eco.internal.config.EcoLoadableConfig.init(EcoLoadableConfig.kt:98) ~[?:?]
	at com.willfp.eco.internal.config.EcoLoadableConfig.<init>(EcoLoadableConfig.kt:147) ~[?:?]
	at com.willfp.eco.internal.config.EcoUpdatableConfig.<init>(EcoUpdatableConfig.kt:19) ~[?:?]
	at com.willfp.eco.internal.spigot.EcoImpl.createUpdatableConfig(EcoImpl.kt:170) ~[?:?]
	at com.willfp.eco.internal.spigot.EcoImpl.createUpdatableConfig(EcoImpl.kt:77) ~[?:?]
	at com.willfp.eco.core.config.BaseConfig.<init>(BaseConfig.java:43) ~[?:?]
	at com.willfp.eco.core.config.BaseConfig.<init>(BaseConfig.java:26) ~[?:?]
	at com.willfp.eco.core.config.base.LangYml.<init>(LangYml.java:41) ~[?:?]
	at com.willfp.eco.core.EcoPlugin.createLangYml(EcoPlugin.java:848) ~[?:?]
	at com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:338) ~[?:?]
	at com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:180) ~[?:?]
	at com.willfp.eco.internal.spigot.EcoSpigotPlugin.<init>(EcoSpigotPlugin.kt:140) ~[?:?]
	at com.willfp.eco.internal.spigot.EcoImpl.<init>(EcoImpl.kt:78) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:79) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	... 7 more`

Server Information
- Version: Spigot MC for 1.20
- Version of plugin: eco 6.63.1, ecoenchants 10.19.0, ProtocolLib build 652

**Comment by MagicTeaMC** [comment]
same as https://github.com/Auxilor/eco/issues/277

**Comment by kylichist** [comment]
Fixed with 6.64.0
