### ISSUE TITLE
Circular plugin loading detected

### ISSUE THREAD

**Issue by bananaQwQ666** [Auxilor/eco#340]
**Is your feature request related to a problem? Please describe.**
When I start the server, the server reports the error "Circular plugin loading detected"
**Describe the solution you'd like**
I hope the server can load normally

**Describe alternatives you've considered**
If I can't solve this problem, I can only delete the eco and ecoenchants

**Additional context**
`[18:21:25] [Server thread/ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[18:21:25] [Server thread/ERROR]: [SimpleProviderStorage] Circular load order:
[18:21:25] [Server thread/ERROR]: [SimpleProviderStorage]   eco -> DeluxeMenus -> ItemsAdder -> MMOItems -> Residence -> CMI -> Jobs -> EcoEnchants -> eco
[18:21:25] [Server thread/ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[18:21:25] [Server thread/ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[18:21:25] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins eco
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[paper-1.20.1.jar:git-Paper-84]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:43) ~[paper-1.20.1.jar:git-Paper-84]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-84]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-84]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by WillFP** [comment]
Follow advice from https://github.com/Auxilor/eco/issues/346
