### ISSUE TITLE
[Warning] Cannot invoke "String.isEmpty()" because "text" is null

### ISSUE THREAD

**Issue by SandTripper** [Auxilor/eco#342]
That is warning stack
[16:38:30 WARN]: [eco] Exception in packet listener com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.display.PacketWindowItems for packet net.minecraft.network.protocol.game.PacketPlayOutWindowItems!
[16:38:30 WARN]: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "text" is null
[16:38:30 WARN]:        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.component(LegacyComponentSerializerImpl.java:326)
[16:38:30 WARN]:        at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.lambda$flattener$3(ComponentFlattenerImpl.java:117)
[16:38:30 WARN]:        at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:95)
[16:38:30 WARN]:        at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:78)
[16:38:30 WARN]:        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:271)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2677)
[16:38:30 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2675)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2658)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.util.StringUtils.toLegacy(StringUtils.java:620)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.item.EcoFastItemStack.getLore(EcoFastItemStack.kt:125)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.core.display.Display.revert(Display.java:144)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.core.display.Display.display(Display.java:70)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.display.PacketWindowItems.modifyWindowItems(PacketWindowItems.kt:83)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.display.PacketWindowItems.onSend(PacketWindowItems.kt:49)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.events.EcoEventManagerKt.handleSend(EcoEventManager.kt:26)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.EcoChannelDuplexHandler.write(EcoChannelDuplexHandler.kt:39)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:38:30 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:38:30 WARN]:        at Model-Engine-R3.1.8.jar//com.ticxo.modelengine.nms.v1_20_R1.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:85)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:38:30 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:38:30 WARN]:        at TAB-Bridge v5.0.1.jar//me.neznamy.tab.bridge.bukkit.BridgeChannelDuplexHandler.write(BridgeChannelDuplexHandler.java:35)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[16:38:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[16:38:30 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[16:38:30 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[16:38:30 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:476)
[16:38:30 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:450)
[16:38:30 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[16:38:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:38:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:38:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:38:30 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[16:38:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:38:30 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:38:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:38:30 WARN]: [eco] Exception in packet listener com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.display.PacketWindowItems for packet net.minecraft.network.protocol.game.PacketPlayOutWindowItems!
[16:38:30 WARN]: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "text" is null
[16:38:30 WARN]:        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.component(LegacyComponentSerializerImpl.java:326)
[16:38:30 WARN]:        at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.lambda$flattener$3(ComponentFlattenerImpl.java:117)
[16:38:30 WARN]:        at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:95)
[16:38:30 WARN]:        at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:78)
[16:38:30 WARN]:        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:271)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2677)
[16:38:30 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2675)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2658)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.util.StringUtils.toLegacy(StringUtils.java:620)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.item.EcoFastItemStack.getLore(EcoFastItemStack.kt:125)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.core.display.Display.revert(Display.java:144)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.core.display.Display.display(Display.java:70)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.display.PacketWindowItems.modifyWindowItems(PacketWindowItems.kt:83)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.display.PacketWindowItems.onSend(PacketWindowItems.kt:49)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.events.EcoEventManagerKt.handleSend(EcoEventManager.kt:26)
[16:38:30 WARN]:        at eco-6.68.3-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.EcoChannelDuplexHandler.write(EcoChannelDuplexHandler.kt:39)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:38:30 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:38:30 WARN]:        at Model-Engine-R3.1.8.jar//com.ticxo.modelengine.nms.v1_20_R1.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:85)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:38:30 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:38:30 WARN]:        at TAB-Bridge v5.0.1.jar//me.neznamy.tab.bridge.bukkit.BridgeChannelDuplexHandler.write(BridgeChannelDuplexHandler.java:35)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[16:38:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[16:38:30 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[16:38:30 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[16:38:30 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[16:38:30 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:476)
[16:38:30 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:450)
[16:38:30 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[16:38:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:38:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:38:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:38:30 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[16:38:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:38:30 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:38:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by SandTripper** [comment]
eco version: 6.68.3

**Comment by SandTripper** [comment]
It will be triggered when any player opens the inventory, whether it is the menu of other plugins or the backpack.

**Comment by WillFP** [comment]
fixed
