### ISSUE TITLE
Could not pass event PlayerJoinEvent to eco v6.68.6

### ISSUE THREAD

**Issue by fishylunar** [Auxilor/eco#345]
**Describe the bug**
Exception thrown on player join

**To Reproduce**
1. Join

**Expected behavior**
Plugin works as expected

**Screenshots**
**Server Information (please complete the following information):**
- Version: 3871-spigot-d2eba2c-3f9263b 1.20.1 (API version: 1.20.1-r01-snapshot)
- Eco v6.68.6, EcoEnchants: 12.2.3, EcoSkills: 3.43.1

**Additional context**
Other plugins  LuckPerms, MVdWPlaceholderAPI, PlaceholderAPI, NBTAPI, Vault, FastAsyncWorldEdit (WorldEdit), Essentials, ItemRarity, WorldGuard, eco, EcoSkills, EcoEnchants, LevelledMobs, libreforge

**Log output**
```plaintext
[23:54:27] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to eco v6.68.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.a(PlayerList.java:308) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.LoginListener.a(LoginListener.java:183) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.LoginListener.d(LoginListener.java:169) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.LoginListener.c(LoginListener.java:75) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:285) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:175) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1323) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1014) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalAccessError: class com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.PacketInjectorListener tried to access private field net.minecraft.server.network.PlayerConnection.h (com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.PacketInjectorListener is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @45cd9472; net.minecraft.server.network.PlayerConnection is in unnamed module of loader java.net.URLClassLoader @31221be2)
	at com.willfp.eco.internal.spigot.proxy.v1_20_R1.common.packet.PacketInjectorListener.onJoin(PacketInjectorListener.kt:17) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 15 more
```

**Comment by WillFP** [comment]
fixed
