### ISSUE TITLE
[BUG report] Circular plugin loading detected

### ISSUE THREAD

**Issue by Yurium7** [Auxilor/eco#346]
[14:46:32 ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[14:46:32 ERROR]: [SimpleProviderStorage] Circular load order:
[14:46:32 ERROR]: [SimpleProviderStorage]   CMI -> eco -> ItemsAdder -> EnchantSlots -> MMOItems -> MMOCore -> Residence -> CMI
[14:46:32 ERROR]: [SimpleProviderStorage]   CMI -> eco -> ItemsAdder -> EnchantSlots -> EcoEnchants -> CMI
[14:46:32 ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[14:46:32 ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[14:46:32 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins CMI, CMI
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:43) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

eco is 6.69.0 / ecoenchant is 12.3.0

**Comment by MedvedEE** [comment]
[12:03:41] [Server thread/ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[12:03:41] [Server thread/ERROR]: [SimpleProviderStorage] Circular load order:
[12:03:41] [Server thread/ERROR]: [SimpleProviderStorage]   Jobs -> EcoEnchants -> eco -> ShopGUIPlus -> ItemsAdder -> CMI -> Jobs
[12:03:41] [Server thread/ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[12:03:41] [Server thread/ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[12:03:41] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins Jobs
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:42) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1134) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[pufferfish-1.20.4.jar:git-Pufferfish-39]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
	
	
	Same thing with Jobs

**Comment by MedvedEE** [comment]
Great support!

**Comment by refractored** [comment]
Add the startup flag ``-Dpaper.useLegacyPluginLoading=true`` to fix this

**Comment by WillFP** [comment]
Should be fixed with new versions of eco, if not then follow the advice from @refractored
