### ISSUE TITLE
[Bug Report] The plugin can be used normally, but the console is full of Error information

### ISSUE THREAD

**Issue by Yurium7** [Auxilor/eco#360]
**Describe the bug**
The plugin can be used normally, but the console is full of Error information

**To Reproduce**
1. Add plugins
2. Restart the server

**Expected behavior**
Fix this content

**Server Information (please complete the following information):**
- Version: 
This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
- Version of plugin and eco:
eco version 6.71.3
ecoenchant version 12.9.1

**Additional context**
[13:35:41 ERROR]: Fatal error trying to convert EcoEnchants v12.9.1:com/willfp/ecoenchants/EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.class
java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199) ~[asm-9.4.jar:9.4]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.4.jar:9.4]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.4.jar:9.4]
        at org.bukkit.craftbukkit.v1_19_R3.util.Commodore.convert(Commodore.java:171) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:405) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:206) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin.handleEnable(EcoEnchantsPlugin.kt:158) ~[EcoEnchantsv12.9.1.jar:?]
        at com.willfp.eco.core.EcoPlugin.handleLifecycle(EcoPlugin.java:722) ~[eco-6.71.3-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.onEnable(EcoPlugin.java:461) ~[eco-6.71.3-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

[13:36:08 ERROR]: Fatal error trying to convert libreforge v4.62.1:com/willfp/libreforge/effects/executors/ChainExecutors.class
java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199) ~[asm-9.4.jar:9.4]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.4.jar:9.4]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.4.jar:9.4]
        at org.bukkit.craftbukkit.v1_19_R3.util.Commodore.convert(Commodore.java:171) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:405) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:206) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at com.willfp.libreforge.effects.Effects.compile(Effects.kt:72) ~[libreforge-4.62.1.jar:?]
        at com.willfp.libreforge.effects.Effects.compile(Effects.kt:48) ~[libreforge-4.62.1.jar:?]
        at com.willfp.ecoskills.LevellableWithHolder.<init>(LevellableWithHolder.kt:22) ~[EcoSkillsv3.50.1.jar:?]
        at com.willfp.ecoskills.stats.Stat.<init>(Stat.kt:21) ~[EcoSkillsv3.50.1.jar:?]
        at com.willfp.ecoskills.stats.Stats.acceptConfig(Stats.kt:31) ~[EcoSkillsv3.50.1.jar:?]
        at com.willfp.ecoskills.libreforge.loader.LibreforgePlugin$loadCategory$3.invoke(LibreforgePlugin.kt:100) ~[EcoSkillsv3.50.1.jar:?]
        at com.willfp.ecoskills.libreforge.loader.LibreforgePlugin$loadCategory$3.invoke(LibreforgePlugin.kt:95) ~[EcoSkillsv3.50.1.jar:?]
        at com.willfp.ecoskills.libreforge.loader.LibreforgePlugin.withLogs(LibreforgePlugin.kt:131) ~[EcoSkillsv3.50.1.jar:?]
        at com.willfp.ecoskills.libreforge.loader.LibreforgePlugin.loadCategory(LibreforgePlugin.kt:95) ~[EcoSkillsv3.50.1.jar:?]
        at com.willfp.ecoskills.libreforge.loader.LibreforgePlugin.loadCategory$default(LibreforgePlugin.kt:84) ~[EcoSkillsv3.50.1.jar:?]
        at com.willfp.ecoskills.libreforge.loader.LibreforgePlugin._init_$lambda$6(LibreforgePlugin.kt:79) ~[EcoSkillsv3.50.1.jar:?]
        at com.willfp.eco.core.EcoPlugin.handleLifecycle(EcoPlugin.java:713) ~[eco-6.71.3-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.reload(EcoPlugin.java:639) ~[eco-6.71.3-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.lambda$onEnable$6(EcoPlugin.java:439) ~[eco-6.71.3-all.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1115) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by WillFP** [comment]
Not an eco bug, but has been fixed with new versions of the plugins.
