### ISSUE TITLE
Fatal error with proxies on purpur 1.20.6

### ISSUE THREAD

**Issue by MelodyYuuka** [Auxilor/eco#361]
**Describe the bug**
When I run eco on purpur 1.20.6, he reports an error that doesn't work

**To Reproduce**
1. Use purpur 1.20.6
2. Add eco 6.71.4
3. Start the server

**Expected behavior**
work on purpur 1.20.6

**Server Information (please complete the following information):**
- Version: Current Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*
* You are running the latest version
Previous: git-Purpur-2174 (MC: 1.20.4)
- Version of plugin and eco： eco 6.71.4

**Additional context**
[23:31:42] [Server thread/ERROR]: [eco] Fatal error with proxies! This plugin can't load.
[23:31:42] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'eco-6.71.4-all.jar' in folder 'plugins/.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `com.willfp.eco.internal.spigot.EcoImpl'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 10 more
Caused by: com.willfp.eco.core.proxy.exceptions.ProxyError: Could not initialize proxy.
	at eco-6.71.4-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.proxyErrorFrom(EcoProxyFactory.kt:47) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.getProxy(EcoProxyFactory.kt:37) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.core.EcoPlugin.getProxy(EcoPlugin.java:940) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.spigot.EcoImpl.formatMiniMessage(EcoImpl.kt:312) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.util.StringUtils.translateMiniMessage(StringUtils.java:404) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.util.StringUtils.processFormatting(StringUtils.java:396) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:183) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2677) ~[eco-6.71.4-all.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2675) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2658) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:58) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.util.StringUtils.format(StringUtils.java:354) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.util.StringUtils.format(StringUtils.java:268) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.logging.EcoLogger.info(EcoLogger.kt:11) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:328) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:180) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.spigot.EcoSpigotPlugin.<init>(EcoSpigotPlugin.kt:147) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.spigot.EcoImpl.<init>(EcoImpl.kt:82) ~[eco-6.71.4-all.jar:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 10 more
Caused by: com.willfp.eco.core.proxy.exceptions.UnsupportedVersionError: You're running an unsupported server version: v1_20_6
	at eco-6.71.4-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.proxyErrorFrom(EcoProxyFactory.kt:49) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.getProxy(EcoProxyFactory.kt:37) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.core.EcoPlugin.getProxy(EcoPlugin.java:940) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.spigot.EcoImpl.formatMiniMessage(EcoImpl.kt:312) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.util.StringUtils.translateMiniMessage(StringUtils.java:404) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.util.StringUtils.processFormatting(StringUtils.java:396) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:183) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2677) ~[eco-6.71.4-all.jar:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2675) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2658) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:58) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.util.StringUtils.format(StringUtils.java:354) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.util.StringUtils.format(StringUtils.java:268) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.logging.EcoLogger.info(EcoLogger.kt:11) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:328) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:180) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.spigot.EcoSpigotPlugin.<init>(EcoSpigotPlugin.kt:147) ~[eco-6.71.4-all.jar:?]
	at eco-6.71.4-all.jar/com.willfp.eco.internal.spigot.EcoImpl.<init>(EcoImpl.kt:82) ~[eco-6.71.4-all.jar:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 10 more

**Comment by efekurbann** [comment]
Having the same issue. On Purpur 1.20.6 with eco 6.71.4 and ecopets 2.64.0

**Comment by fukiame** [comment]
support for 1.20.6 was dropped at 9b47e4777a92daf66ecd4e39d1d9228c06fe29ee.
since Polymart does not seem to provide downloads for old versions of the plugin,
either compile it yourself before that commit or use [the last github actions artifact](https://github.com/Auxilor/eco/actions/runs/9628325071) for it.

**Comment by WillFP** [comment]
1.20.6 isn't supported, I've explained before on discord but the tl;dr is that it was a transition version between 1.20.4 and 1.21 and is unreasonably annoying to support, personal view is that it should have just been a snapshot.

If you're on a dev server I recommend upgrading to 1.21, if you're in prod then either downgrade to 1.20.4 or wait a few days until 1.21 is officially supported by paper.
