### ISSUE TITLE
Crashing on startup in newest version

### ISSUE THREAD

**Issue by FearlessNite345** [Auxilor/eco#367]
[19:24:33 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'eco-6.73.2-all.jar' in folder 'plugins/.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `com.willfp.eco.internal.spigot.EcoImpl'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.NoClassDefFoundError: com/willfp/eco/internal/EcoPropsParser
        at eco-6.73.2-all.jar/com.willfp.eco.internal.spigot.EcoImpl.getProps(EcoImpl.kt:306) ~[eco-6.73.2-all.jar:?]
        at eco-6.73.2-all.jar/com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:329) ~[eco-6.73.2-all.jar:?]
        at eco-6.73.2-all.jar/com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:191) ~[eco-6.73.2-all.jar:?]
        at eco-6.73.2-all.jar/com.willfp.eco.internal.spigot.EcoSpigotPlugin.<init>(EcoSpigotPlugin.kt:151) ~[eco-6.73.2-all.jar:?]
        at eco-6.73.2-all.jar/com.willfp.eco.internal.spigot.EcoImpl.<init>(EcoImpl.kt:82) ~[eco-6.73.2-all.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: com.willfp.eco.internal.EcoPropsParser
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at eco-6.73.2-all.jar/com.willfp.eco.internal.spigot.EcoImpl.getProps(EcoImpl.kt:306) ~[eco-6.73.2-all.jar:?]
        at eco-6.73.2-all.jar/com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:329) ~[eco-6.73.2-all.jar:?]
        at eco-6.73.2-all.jar/com.willfp.eco.core.EcoPlugin.<init>(EcoPlugin.java:191) ~[eco-6.73.2-all.jar:?]
        at eco-6.73.2-all.jar/com.willfp.eco.internal.spigot.EcoSpigotPlugin.<init>(EcoSpigotPlugin.kt:151) ~[eco-6.73.2-all.jar:?]
        at eco-6.73.2-all.jar/com.willfp.eco.internal.spigot.EcoImpl.<init>(EcoImpl.kt:82) ~[eco-6.73.2-all.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 10 more

**Comment by Hahaa13** [comment]
ecoitems is the same
