### ISSUE TITLE
Cannot invoke "String.isEmpty()" because "text" is null

### ISSUE THREAD

**Issue by jimi1104** [Auxilor/eco#376]
`[01:55:55 WARN]: [eco] Exception in packet listener com.willfp.eco.internal.spigot.proxy.v1_20_R2.common.packet.display.PacketSetSlot for packet net.minecraft.network.protocol.game.PacketPlayOutSetSlot!
[01:55:55 WARN]: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "text" is null
[01:55:55 WARN]:        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.component(LegacyComponentSerializerImpl.java:326)
[01:55:55 WARN]:        at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.lambda$flattener$3(ComponentFlattenerImpl.java:117)
[01:55:55 WARN]:        at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:95)
[01:55:55 WARN]:        at net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:78)
[01:55:55 WARN]:        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:271)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2677)
[01:55:55 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2675)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2658)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.willfp.eco.util.StringUtils.toLegacy(StringUtils.java:620)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R2.common.item.EcoFastItemStack.getLore(EcoFastItemStack.kt:137)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.willfp.eco.core.display.Display.revert(Display.java:144)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.willfp.eco.core.display.Display.display(Display.java:70)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R2.common.packet.display.PacketSetSlot.onSend(PacketSetSlot.kt:15)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.willfp.eco.internal.events.EcoEventManagerKt.handleSend(EcoEventManager.kt:26)
[01:55:55 WARN]:        at eco-6.73.6-all.jar//com.willfp.eco.internal.spigot.proxy.v1_20_R2.common.packet.EcoChannelDuplexHandler.write(EcoChannelDuplexHandler.kt:39)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[01:55:55 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[01:55:55 WARN]:        at MythicMobs-5.6.1[tinksp.com].jar//io.lumine.mythic.core.volatilecode.v1_20_R2.packets.VolatileChannelHandler.write(VolatileChannelHandler.java:76)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[01:55:55 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[01:55:55 WARN]:        at MagicCosmetics-3.0.5[tinksp.com].jar//com.francobm.magicosmetics.nms.v1_20_R2.models.MCChannelHandler.write(MCChannelHandler.java:69)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[01:55:55 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[01:55:55 WARN]:        at TAB.v4.1.2.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[01:55:55 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[01:55:55 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[01:55:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[01:55:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[01:55:55 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:449)
[01:55:55 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:434)
[01:55:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[01:55:55 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[01:55:55 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[01:55:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[01:55:55 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[01:55:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:55:55 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:55:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by jimi1104** [comment]
eco version: 6.73.6

**Comment by jimi1104** [comment]
When I use some containers and itemsadder's items, it reports.

**Comment by jimi1104** [comment]
eco version: 6.73.7
