### ISSUE TITLE
Support for 1.20.6

### ISSUE THREAD

**Issue by RNAmaya** [Auxilor/eco#379]
# Hello Auxilor team
I would like to propose that you add
support for version 1.20.6 since it is a version that is used
on many servers including myself and since the echo plugin is a dependency
it does not allow the other plugins to initialize so I propose that you can add support.

**Comment by Walabise** [comment]
`[16:39:33 ERROR]: [eco] Fatal error with proxies! This plugin can't load.
[16:39:33 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'eco-6.74.2-all.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `com.willfp.eco.internal.spigot.EcoImpl'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:532) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 10 more`
