### ISSUE TITLE
Error in console on paper-1.21-130

### ISSUE THREAD

**Issue by TheReizi** [Auxilor/eco#381]
**Describe the bug**
The plugin was fine for a long time, but one of the launches, for some reason it stopped launching with the error below

Is it possible that this is due to plugins that depend on it? such as EcoEnchants, Actions?

**To Reproduce**
1. Put eco plugin in plugins
2. Run Paper-1.21-130 core
3. Get error

**Expected behavior**
Launching and functioning of the plugin

**Screenshots**

**Server Information (please complete the following information):**
The plugin version is listed below

**Additional context**
`[10:48:10 INFO]: [eco] Initializing eco
[10:48:10 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'eco-6.74.2-all.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `com.willfp.eco.internal.spigot.EcoImpl'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:547) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/inventory/CraftItemStack
        at eco-6.74.2-all.jar/com.willfp.eco.internal.spigot.proxy.v1_21.CommonsInitializer$CommonsProviderImpl.<clinit>(CommonsInitializer.kt:47) ~[eco-6.74.2-all.jar:?]
        at eco-6.74.2-all.jar/com.willfp.eco.internal.spigot.proxy.v1_21.CommonsInitializer.init(CommonsInitializer.kt:40) ~[eco-6.74.2-all.jar:?]
        at eco-6.74.2-all.jar/com.willfp.eco.internal.spigot.EcoImpl.<init>(EcoImpl.kt:86) ~[eco-6.74.2-all.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R1.inventory.CraftItemStack
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at eco-6.74.2-all.jar/com.willfp.eco.internal.spigot.proxy.v1_21.CommonsInitializer$CommonsProviderImpl.<clinit>(CommonsInitializer.kt:47) ~[eco-6.74.2-all.jar:?]
        at eco-6.74.2-all.jar/com.willfp.eco.internal.spigot.proxy.v1_21.CommonsInitializer.init(CommonsInitializer.kt:40) ~[eco-6.74.2-all.jar:?]
        at eco-6.74.2-all.jar/com.willfp.eco.internal.spigot.EcoImpl.<init>(EcoImpl.kt:86) ~[eco-6.74.2-all.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more`

**Comment by TheReizi** [comment]
Only deleting the paper-remapped folder helps
