### ISSUE TITLE
"Unhandled exception occured in onPacketSending(PacketEvent)" when viewing villager trades

### ISSUE THREAD

**Issue by cykreet** [Auxilor/eco#4]
Any information regarding the issue would be really appreciated. Apologies in advance if I've misunderstood the issue or cause any inconvenience.

Running the following plugin versions on a Paper 1.16.5 (build: 465) server:
`eco  v3.6.0`
`ProtocolLib v4.5.1`
`EcoEnchants v6.5.2`

Full Stacktrace:
```
[15:41:50 ERROR]: [eco] Unhandled exception occured in onPacketSending(PacketEvent) for eco
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.events.PacketContainer.getMerchantRecipeLists()'
        at com.willfp.eco.spigot.display.packets.PacketOpenWindowMerchant.onSend(PacketOpenWindowMerchant.java:29) ~[?:?]
        at com.willfp.eco.util.protocollib.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:115) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1709) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.EntityPlayer.openTrade(EntityPlayer.java:1325) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.IMerchant.openTrade(IMerchant.java:42) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.EntityVillager.h(EntityVillager.java:264) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.EntityVillager.b(EntityVillager.java:242) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.EntityInsentient.a(EntityInsentient.java:1159) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.EntityHuman.a(EntityHuman.java:908) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2229) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-465]
        at java.lang.Thread.run(Unknown Source) [?:?]
[15:41:50 ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutOpenWindowMerchant@2e268327[
    a=20
    b=[net.minecraft.server.v1_16_R3.MerchantRecipe@2b30b9b9, net.minecraft.server.v1_16_R3.MerchantRecipe@a974ac3, net.minecraft.server.v1_16_R3.MerchantRecipe@28ddd883, net.minecraft.server.v1_16_R3.MerchantRecipe@a1cc9a6, net.minecraft.server.v1_16_R3.MerchantRecipe@24cf442d, net.minecraft.server.v1_16_R3.MerchantRecipe@14bed325]
    c=3
    d=145
    e=true
    f=true
  ]
  ```

**Comment by cykreet** [comment]
Pretty much a duplicate of: https://github.com/Auxilor/EcoEnchants/pull/27

**Comment by Auxilor** [comment]
your protocollib is outdated https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by cykreet** [comment]
yikes, that's my bad. thanks for your time ❤
