### ISSUE TITLE
Potential performance issue and/or bug

### ISSUE THREAD

**Issue by newtykins** [Auxilor/eco#54]
A server I am working on has recently been transferring its data to MySQL and a plugin called LagMonitor reported this about your plugin as we enabled it. The server also has degraded performance. I was wondering if you could offer some insight?

```
[23:36:42 WARN]: [LagMonitor] Loaded class com.willfp.eco.spigot.data.storage.MySQLDataHandler$getPlayer$player$1 from eco v6.13.2 which is not a depend, softdepend or loadbefore of this plugin.
[23:36:42 WARN]: [LagMonitor] Plugin eco is performing a blocking I/O operation (Socket: socket://localhost:3306) on the main thread. This could affect the server performance, because the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time. Keep in mind to keep the code thread-safe. Report it to the plugin author
[23:36:42 WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developers to find the source. LagMonitor doesn't prevent this action. It just warns you about it.
java.lang.IllegalAccessException: null
        at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:65) ~[LagMonitor.jar:?]
        at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:51) ~[LagMonitor.jar:?]
        at com.github.games647.lagmonitor.listener.BlockingConnectionSelector.select(BlockingConnectionSelector.java:30) ~[LagMonitor.jar:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:316) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[patched_1.17.1.jar:git-Paper-380]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[patched_1.17.1.jar:git-Paper-380]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:144) ~[patched_1.17.1.jar:git-Paper-380]
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953) ~[patched_1.17.1.jar:git-Paper-380]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823) ~[patched_1.17.1.jar:git-Paper-380]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[patched_1.17.1.jar:git-Paper-380]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[patched_1.17.1.jar:git-Paper-380]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[patched_1.17.1.jar:git-Paper-380]
        at java.sql.DriverManager.getConnection(DriverManager.java:681) ~[java.sql:?]
        at java.sql.DriverManager.getConnection(DriverManager.java:229) ~[java.sql:?]
        at org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:206) ~[?:?]
        at org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:206) ~[?:?]
        at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:127) ~[?:?]
        at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:128) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:68) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:67) ~[?:?]
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:74) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt) ~[?:?]
        at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:24) ~[?:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:47) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:133) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:119) ~[?:?]
        at org.jetbrains.exposed.sql.AbstractQuery.iterator(AbstractQuery.kt:61) ~[?:?]
        at kotlin.collections.CollectionsKt___CollectionsKt.singleOrNull(_Collections.kt:637) ~[?:?]
        at com.willfp.eco.spigot.data.storage.MySQLDataHandler$getPlayer$player$1.invoke(MySQLDataHandler.kt:169) ~[eco-6.13.2-all.jar:?]
        at com.willfp.eco.spigot.data.storage.MySQLDataHandler$getPlayer$player$1.invoke(MySQLDataHandler.kt:168) ~[eco-6.13.2-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:142) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:221) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:134) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:131) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:130) ~[?:?]
        at com.willfp.eco.spigot.data.storage.MySQLDataHandler.getPlayer(MySQLDataHandler.kt:168) ~[eco-6.13.2-all.jar:?]
        at com.willfp.eco.spigot.data.storage.MySQLDataHandler.access$getPlayer(MySQLDataHandler.kt:31) ~[eco-6.13.2-all.jar:?]
        at com.willfp.eco.spigot.data.storage.MySQLDataHandler$read$1.invoke(MySQLDataHandler.kt:128) ~[eco-6.13.2-all.jar:?]
        at com.willfp.eco.spigot.data.storage.MySQLDataHandler$read$1.invoke(MySQLDataHandler.kt:127) ~[eco-6.13.2-all.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:187) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:213) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:221) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:212) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:164) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:221) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:134) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:131) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:130) ~[?:?]
        at com.willfp.eco.spigot.data.storage.MySQLDataHandler.read(MySQLDataHandler.kt:127) ~[eco-6.13.2-all.jar:?]
        at com.willfp.eco.spigot.data.EcoPlayerProfileHandler.load(EcoPlayerProfileHandler.kt:27) ~[eco-6.13.2-all.jar:?]
        at com.willfp.eco.core.data.PlayerProfile.load(PlayerProfile.java:54) ~[eco-6.13.2-all.jar:?]
        at com.willfp.eco.core.data.PlayerProfile.load(PlayerProfile.java:43) ~[eco-6.13.2-all.jar:?]
        at com.willfp.ecoskills.EcoSkillsPlayerKt.getSkillLevel(EcoSkillsPlayer.kt:98) ~[EcoSkills v1.11.3.jar:?]
        at com.willfp.ecoskills.data.LeaderboardHandler$Runnable.run(LeaderboardHandler.kt:47) ~[EcoSkills v1.11.3.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-380]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-380]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-380]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-380]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-380]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-380]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-380]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]****
```

**Comment by WillFP** [comment]
Update to latest version, MySQL has been rewritten several times
