### ISSUE TITLE
1.17.1 Error

### ISSUE THREAD

**Issue by AlphineGhost** [Auxilor/eco#59]
`[13:03:41] [Server thread/ERROR]: [eco] Unhandled exception occured in onPacketSending(PacketEvent) for eco
java.lang.IllegalAccessError: class com.willfp.eco.proxy.v1_17_R1.fast.NMSFastItemStack tried to access private field net.minecraft.world.item.ItemStack.u (com.willfp.eco.proxy.v1_17_R1.fast.NMSFastItemStack is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2290cf2b; net.minecraft.world.item.ItemStack is in unnamed module of loader 'app')
        at com.willfp.eco.proxy.v1_17_R1.fast.NMSFastItemStack.hashCode(NMSFastItemStack.java:183) ~[eco-6.13.12-all.jar:?]
        at com.willfp.eco.spigot.display.PacketWindowItems.modifyWindowItems(PacketWindowItems.kt:140) ~[eco-6.13.12-all.jar:?]
        at com.willfp.eco.spigot.display.PacketWindowItems.onSend(PacketWindowItems.kt:77) ~[eco-6.13.12-all.jar:?]
        at com.willfp.eco.core.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:119) ~[eco-6.13.12-all.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:4.7.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:4.7.0]
        at net.minecraft.network.NetworkManager.b(NetworkManager.java:203) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:183) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1695) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.network.PlayerConnection.sendPacket(PlayerConnection.java:1681) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.level.EntityPlayer$1.sendInitialData(EntityPlayer.java:246) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.Container.updateInventory(Container.java:189) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.Container.a(Container.java:169) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.level.EntityPlayer.initMenu(EntityPlayer.java:542) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.level.EntityPlayer.syncInventory(EntityPlayer.java:546) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:381) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:192) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.network.LoginListener.c(LoginListener.java:179) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1336) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:03:41] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutWindowItems@3a2ad0eb[
    a=0
    b=1
    c=[1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 diamond_chestplate, 1 diamond_leggings, 1 diamond_boots, 2 arrow, 2 bone, 2 redstone, 18 diamond, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 4 potato, 8 iron_ingot, 64 carrot, 1 diamond_sword, 6 rotten_flesh, 4 string, 1 gunpowder, 40 carrot, 1 spider_eye, 1 air]
    d=1 air
  ]`
  
Error is post startup and when player joins. Is running along side CrazyEnchaments

**Comment by WillFP** [comment]
Update to the latest version of paper
